# Server Configuration
server.port=8080
server.servlet.context-path=/fashionstore

# Thymeleaf Configuration
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8

# Static Resources Configuration
spring.web.resources.static-locations=classpath:/static/
spring.web.resources.add-mappings=true
spring.web.resources.cache.period=0

# Database Configuration (SQL Server)
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=fashion_shopping;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=12345
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

#API Google Oauth2
spring.security.oauth2.client.registration.google.client-id=325759093404-il5n3pdst6nt74no7qeovciisql9kvfo.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret= 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
spring.security.oauth2.client.registration.google.scope=email,profile

# T?ng th?i gian session lên 1 ti?ng (tính b?ng giây ho?c ??nh d?ng ISO-8601)
server.servlet.session.timeout=60m

spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/v2/auth?prompt=select_account