spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: lamhoangkhang180805@gmail.com
    password: vawarlehepfpaikg
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: smtp.gmail.com